import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { FaEye } from "react-icons/fa";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import myteam from "../public/my-team.jpg";
import bookmark from "../public/bookmark-cover.jpg";
import scoot from "../public/scoot.jpg";
import digitalbank from "../public/digitalbank.jpg";

import { useEffect, useRef } from "react";
import restCountries from "../public/restCountries.webp";
import Typed from "typed.js";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const typedElement = useRef(null);

  useEffect(() => {
    const typed = new Typed(typedElement.current, {
      strings: [
        "a Frontend Developer.",
        "a Photographer.",
        "an Amateur Gamer.",
      ],
      typeSpeed: 90,
      backSpeed: 90,
      startDelay: 300,
      backDelay: 90,
      smartBackspace: true,
      showCursor: false,
      loop: true,
    });
    return () => {
      typed.destroy();
    };
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="container mx-auto">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between dark:text-white">
              <h1 className="font-burtons text-2xl">Happinessjon</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                </li>
                <li>
                  <Link
                    className="cursor-pointer"
                    href="https://hh.ru/resume/f83387eeff0b0151690039ed1f7575434b3735?hhtmFrom=resume_list"
                  >
                    <p className="bg-gradient-to-r cursor-pointer from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8">
                      Resume
                    </p>
                  </Link>
                </li>
              </ul>
            </nav>
            <div className="text-center p-10 py-10">
              <h2 className="text-5xl py-2 font-burtons text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
                Abdumalikov Iqboljon
              </h2>
              <h3 className="font-ubuntu font-bold text-2xl inline-block py-2 dark:text-white md:text-3xl">
                I am{" "}
                <span
                  className="text-teal-600 dark:text-teal-400"
                  ref={typedElement}
                ></span>
              </h3>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                Entry-level Software Engineer. <br />
                1+ year of experience in{" "}
                <span className="text-teal-500"> Web Development </span>, 4+
                months real world experience as a Frontend Developer
              </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                <Link href="https://twitter.com/happinessjon">
                  <AiFillTwitterCircle className="cursor-pointer" />
                </Link>
                <Link href="https://www.linkedin.com/in/iqboljonabdumalikov/">
                  <AiFillLinkedin className="cursor-pointer" />
                </Link>
                <Link href="https://github.com/ikboljonabdumalikov">
                  <AiFillGithub className="cursor-pointer" />
                </Link>
              </div>
              <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
                <Image src={deved} layout="fill" objectFit="cover" />
              </div>
            </div>
          </section>
          <section>
            <div className=" text-center">
              <h3 className="font-ubuntu font-bold text-3xl py-1 dark:text-white ">
                Services I offer
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Since the beginning of my journey as a freelance designer and
                developer, I've done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                I offer from a wide range of services, including brand design,
                programming and teaching.
              </p>
            </div>
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <Image src={design} width={100} height={100} />
                <h3 className="font-ubuntu font-bold text-lg pt-8 pb-2  ">
                  Beautiful Layouts
                </h3>
                <p className="py-2">
                  Creating elegant Layouts suited for your needs following core
                  HTML/CSS theory.
                </p>
                <h4 className="font-ubuntu font-bold py-4 text-teal-600">
                  Technologies I Use
                </h4>
                <p className="text-gray-800 py-1">HTML5</p>
                <p className="text-gray-800 py-1">CSS3</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">JavaScript</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <Image src={code} width={100} height={100} />
                <h3 className="font-ubuntu font-bold text-lg pt-8 pb-2 ">
                  Code your dream project
                </h3>
                <p className="py-2">
                  Do you have an idea for your next great website? Let's make it
                  a reality.
                </p>
                <h4 className="font-ubuntu font-bold py-4 text-teal-600">
                  Technologies I Use
                </h4>
                <p className="text-gray-800 py-1">React - Vue.js</p>
                <p className="text-gray-800 py-1">Next.js - Nuxt.js</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">JavaScript</p>
                <p className="text-gray-800 py-1">Tailwind - Windi CSS</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <Image src={consulting} width={100} height={100} />
                <h3 className="font-ubuntu font-bold text-lg pt-8 pb-2 ">
                  Consulting
                </h3>
                <p className="py-2">
                  Are you interested in feedback for your current project? I can
                  give you tips and tricks to level it up.
                </p>
                <h4 className="font-ubuntu font-bold py-4 text-teal-600">
                  Tools I Use
                </h4>
                <p className="text-gray-800 py-1">GitHub</p>
                <p className="text-gray-800 py-1">Debugging</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Code Review</p>
              </div>
            </div>
          </section>
          <section className="py-10">
            <div className="text-center">
              <h3 className="font-ubuntu font-bold text-3xl py-1 dark:text-white ">
                Portfolio
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Since the beginning of my journey as a freelance designer and
                developer, I've done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                I offer from a wide range of services, including brand design,
                programming and teaching.
              </p>
            </div>




            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-xs flex-1 ">
                <Image
                  className="rounded-t-lg object-cover"
                  width={"50%"}
                  height={"50%"}
                  layout="responsive"
                  src={bookmark}
                />
                <div className="flex justify-center items-center bg-teal-500 p-4 rounded-b-lg ">
                  <a href="https://github.com/ikboljonabdumalikov/bookmark">
                    <AiFillGithub className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                  <a href="https://demo-bookmark.netlify.app/">
                    <FaEye className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                </div>
              </div>




              <div className="basis-xs flex-1">
                <Image
                  className="rounded-t-lg object-cover"
                  width={"50%"}
                  height={"50%"}
                  layout="responsive"
                  src={myteam}
                />
                <div className="flex justify-center items-center bg-teal-500 p-4 rounded-b-lg ">
                  <a href="https://github.com/ikboljonabdumalikov/my-team">
                    <AiFillGithub className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                  <a href="https://my-team-demo.netlify.app/">
                    <FaEye className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                </div>
              </div>




              <div className="basis-xs flex-1">
                <Image
                  className="rounded-t-lg object-cover"
                  width={"50%"}
                  height={"50%"}
                  layout="responsive"
                  src={digitalbank}
                />
                <div className="flex justify-center items-center bg-teal-500 p-4 rounded-b-lg ">
                  <a href="https://github.com/ikboljonabdumalikov/easybank-landing-page">
                    <AiFillGithub className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                  <a href="http://easybank-landing-page-black.vercel.app">
                    <FaEye className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                </div>
              </div>




              <div className="basis-xs flex-1">
                <Image
                  className="rounded-t-lg object-cover"
                  width={"50%"}
                  height={"50%"}
                  layout="responsive"
                  src={restCountries}
                />
                <div className="flex justify-center items-center bg-teal-500 p-4 rounded-b-lg ">
                  <a href="https://github.com/ikboljonabdumalikov/rest-countries">
                    <AiFillGithub className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                  <a href="https://rest-countries-delta-bay.vercel.app/">
                    <FaEye className="w-[40px] h-[40px] mx-10 cursor-pointer" />
                  </a>
                </div>
              </div>




              {/*  */}



            </div>
          </section>
        </section>
      </main>
    </div>
  );
}
